version: "3.7"
services:
    demo-api:
        image: username/demo-api:myTag
        build:
          context: .
        ports:
          - 9090:8080
        volumes:
            - ./logs:/logs